FROM golang:latest

WORKDIR C:/Users/richa/GolandProjects/awesomeProject

COPY .env .

COPY logglyassignment.go .

COPY go.mod ./

COPY go.sum ./

ENV LOGGLY_TOKEN=02b996b5-0063-48c7-87e2-fbd03ffac6c0

ENV API_KEY=aqKf60jG6EIL9LqZKSf5KGnRAH1prGPe
